    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest] # later make it work with macos and windows: , macOS-latest, windows-latest]
            cabal: ["3.2"]
            ghc:
              - "8.10.1"
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-haskell@v1.1.1
            id: setup-haskell-cabal
            name: Setup Haskell
            with:
              ghc-version: ${{ matrix.ghc }}
              cabal-version: ${{ matrix.cabal }}

          - name: Install dependencies
            run: |
              cabal v2-update && cabal v2-install hspec-discover
              cabal v2-configure --enable-tests --enable-benchmarks --test-show-details=direct
              
          - name: Freeze
            run: |
              cabal freeze
          - uses: actions/cache@v1
            name: Cache ~/.cabal/store
            with:
              path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
              key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}

          - uses: education/autograding@v1 #Autograding xecutes cabal v2-build and cabal v2-test all
